services:
  graphprocessorapi:
    image: vibecoderhex/graphprocessorapi:latest
    build:
      context: .
      dockerfile: ./GraphProcessorAPI/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
  
  graphprocessorfrontend:
    image: vibecoderhex/graphprocessorfrontend:latest
    build:
      context: ./GraphProcessorFrontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped