// <auto-generated />
using System;
using System.Collections.Generic;
using GraphProcessorAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GraphProcessorAPI.Migrations
{
    [DbContext(typeof(GraphProcessorContext))]
    partial class GraphProcessorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "accountrole", new[] { "User", "Admin" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "algorithm_type", new[] { "Dijkstra", "BFS", "DFS" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "graphtype", new[] { "Oriented", "Non-oriented" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GraphProcessorAPI.Models.Edge", b =>
                {
                    b.Property<int>("EdgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("edge_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EdgeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("description");

                    b.Property<int>("FromNode")
                        .HasColumnType("integer")
                        .HasColumnName("from_node");

                    b.Property<int>("GraphId")
                        .HasColumnType("integer")
                        .HasColumnName("graph_id");

                    b.Property<int>("ToNode")
                        .HasColumnType("integer")
                        .HasColumnName("to_node");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("value");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("EdgeId")
                        .HasName("edge_id_pk");

                    b.HasIndex(new[] { "GraphId" }, "edge_fk_index");

                    b.HasIndex(new[] { "Value", "FromNode", "ToNode" }, "edge_pk")
                        .IsUnique();

                    b.ToTable("edge", (string)null);
                });

            modelBuilder.Entity("GraphProcessorAPI.Models.Graph", b =>
                {
                    b.Property<int>("GraphId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("graph_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GraphId"));

                    b.Property<DateOnly>("Creationat")
                        .HasColumnType("date")
                        .HasColumnName("creationat");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name");

                    b.Property<string>("Structure")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("structure");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("GraphId")
                        .HasName("graph_id_pk");

                    b.HasIndex(new[] { "UserId" }, "graph__fk_index");

                    b.HasIndex(new[] { "Name" }, "graph_unq")
                        .IsUnique();

                    b.ToTable("graph", (string)null);
                });

            modelBuilder.Entity("GraphProcessorAPI.Models.Node", b =>
                {
                    b.Property<int>("NodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("node_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NodeId"));

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<string>("Description")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("description");

                    b.Property<int>("GraphId")
                        .HasColumnType("integer")
                        .HasColumnName("graph_id");

                    b.Property<string>("Image")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("image");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("value");

                    b.HasKey("NodeId")
                        .HasName("node_id_pk");

                    b.HasIndex(new[] { "GraphId" }, "node_fk_index");

                    b.ToTable("node", (string)null);
                });

            modelBuilder.Entity("GraphProcessorAPI.Models.ProcessingResult", b =>
                {
                    b.Property<int>("ProcessingResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("processing_result_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProcessingResultId"));

                    b.Property<int>("GraphId")
                        .HasColumnType("integer")
                        .HasColumnName("graph_id");

                    b.PrimitiveCollection<List<string>>("ShortestPath")
                        .IsRequired()
                        .HasColumnType("character varying(40)[]")
                        .HasColumnName("shortest_path");

                    b.Property<string>("StartVertex")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("start_vertex");

                    b.Property<string>("TargetVertex")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("target_vertex");

                    b.Property<double>("TimeInNs")
                        .HasColumnType("double precision")
                        .HasColumnName("time_in_ns");

                    b.Property<int?>("TotalDistance")
                        .HasColumnType("integer")
                        .HasColumnName("total_distance");

                    b.HasKey("ProcessingResultId")
                        .HasName("processing_result_id_pk");

                    b.HasIndex(new[] { "GraphId" }, "processing_result__fk_index");

                    b.ToTable("processing_result", (string)null);
                });

            modelBuilder.Entity("GraphProcessorAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("password_hash")
                        .IsFixedLength();

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("user_id_pk");

                    b.HasIndex(new[] { "Username", "Email" }, "user_unq")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("GraphProcessorAPI.Models.Edge", b =>
                {
                    b.HasOne("GraphProcessorAPI.Models.Graph", "Graph")
                        .WithMany("Edges")
                        .HasForeignKey("GraphId")
                        .IsRequired()
                        .HasConstraintName("edge_graph_id__fk");

                    b.Navigation("Graph");
                });

            modelBuilder.Entity("GraphProcessorAPI.Models.Graph", b =>
                {
                    b.HasOne("GraphProcessorAPI.Models.User", "User")
                        .WithMany("Graphs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("graph__fk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GraphProcessorAPI.Models.Node", b =>
                {
                    b.HasOne("GraphProcessorAPI.Models.Graph", "Graph")
                        .WithMany("Nodes")
                        .HasForeignKey("GraphId")
                        .IsRequired()
                        .HasConstraintName("node_graph_id__fk");

                    b.Navigation("Graph");
                });

            modelBuilder.Entity("GraphProcessorAPI.Models.ProcessingResult", b =>
                {
                    b.HasOne("GraphProcessorAPI.Models.Graph", "Graph")
                        .WithMany("ProcessingResults")
                        .HasForeignKey("GraphId")
                        .IsRequired()
                        .HasConstraintName("processing_result__fk");

                    b.Navigation("Graph");
                });

            modelBuilder.Entity("GraphProcessorAPI.Models.Graph", b =>
                {
                    b.Navigation("Edges");

                    b.Navigation("Nodes");

                    b.Navigation("ProcessingResults");
                });

            modelBuilder.Entity("GraphProcessorAPI.Models.User", b =>
                {
                    b.Navigation("Graphs");
                });
#pragma warning restore 612, 618
        }
    }
}
