# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: GraphProcessor

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-aspnet-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  build-vite-frontend:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          
      - name: Install dependencies and build frontend
        run: | 
          npm install
          npm run build
        working-directory: ./GraphProcessorFrontend
  
  push-container:
    needs: [build-vite-frontend, build-aspnet-backend]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        run: |
          docker compose build
          docker compose push
  
  deploy-to-server:
    needs: push-container
    runs-on: ubuntu-latest
    
    steps:
      - name: Connect to Fedora server by SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.VDS_HOST }}
          username: ${{ vars.VDS_USERNAME }}
          key: ${{ secrets.VDS_SSH_KEY }}
          script: |
            cd graph_processor
            docker compose down
            docker compose pull
            docker compose up -d
            fastfetch